image: code.yzzzz.com.cn:5000/python:3.10

stages:
  - test
  - deploy

test-job:
  stage: test
  script:
    - pip install .[test] -i http://mirrors.aliyun.com/pypi/simple
    - python -m pytest

deploy-job:
  stage: deploy
  script:
    - pip install . -i http://mirrors.aliyun.com/pypi/simple
    - python -m ditto.main sim