image: code.yzzzz.com.cn:5000/python:3.10

stages:
  - test
  - deploy

test-job:
  stage: test
  script:
    - pip install .[test] -i https://pypi.tuna.tsinghua.edu.cn/simple
    - python -m pytest

deploy-job:
  stage: deploy
  script:
    - pip install . -i https://pypi.tuna.tsinghua.edu.cn/simple
    - python -m ditto.main